import type { Metadata, Viewport } from "next";
import { Geist, Geist_Mono, Hind_Siliguri } from "next/font/google";
import "./globals.css";
import Providers from "./providers";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// Bengali (Bangla) text needs a font that actually covers the script.
// Geist only ships a "latin" subset, so on phones without a built-in
// Bangla system font, Bangla characters can fail to render properly.
const hindSiliguri = Hind_Siliguri({
  variable: "--font-bangla",
  subsets: ["bengali", "latin"],
  weight: ["400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// Next.js does inject a default viewport tag automatically, but it does NOT
// include viewport-fit=cover, which is required for env(safe-area-inset-*)
// to work (needed for fixed bottom bars on iPhones with a home indicator).
export const viewport: Viewport = {
  width: "device-width",
  initialScale: 1,
  viewportFit: "cover",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} ${hindSiliguri.variable} h-full antialiased`}
    >
      <body className="min-h-full min-h-[100dvh] flex flex-col">
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
